version: '3.6'

services:
  mysql:
    image: mysql:8.0.15
    container_name: microdust-db
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d/my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf:ro
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: microdust
      MYSQL_USER: microdust
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul

  mongodb:
    image: mongo:latest
    container_name: microdust-mongodb
    volumes:
      - ./mongodb/data:/data/db
      - ./mongodb/log:/data/log
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/data/log

  myapp:
    depends_on:
      - mysql
    image: ifjso/myapp:1.0
    container_name: testapp
    restart: always
    ports:
      - 8080:8080
    environment:
      TZ: Asia/Seoul
