version: '3.6'

services:
  mysql:
    image: mysql:8.0.15
    container_name: microdust-db
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf.d/my_custom.cnf:/etc/mysql/conf.d/my_custom.cnf:ro
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: microdust
      MYSQL_USER: microdust
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: Asia/Seoul
